import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import { CssBaseline } from "@mui/material";
import theme from "@/theme";
import NavBar from "@/componentes/navbar/Navbar";
import Footer from "@/componentes/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aqua Maris Hotels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <NavBar />
          <main className="flex-grow">{children}</main>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
