import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button, CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aqua Maris Hotels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <ThemeProvider theme={theme}>
        <CssBaseline />
          <main className="flex-grow">{children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
